JOBS = [
    {
        "id": 1,
        "title": "Entry-level Web Developer",
        "company": "Kigali Devs",
        "location": "Kigali, Rwanda",
        "industry": "Technology",
        "jobType": "Full-time",
        "experienceLevel": "Entry",
        "postedDate": "2025-08-01",
        "salaryRange": {"min": 150000, "max": 300000, "currency": "RWF"},
        "required_skills": ["html", "css", "javascript"]
    },
    {
        "id": 2,
        "title": "Frontend Developer (React)",
        "company": "Fintech Innovators Rwanda",
        "location": "Kigali, Rwanda",
        "industry": "Fintech",
        "jobType": "Full-time",
        "experienceLevel": "Mid-level",
        "postedDate": "2025-07-28",
        "salaryRange": {"min": 400000, "max": 600000, "currency": "RWF"},
        "required_skills": ["html", "css", "javascript", "react", "git"]
    },
    {
        "id": 3,
        "title": "Backend Developer (Python)",
        "company": "Africa Solutions Ltd",
        "location": "Remote",
        "industry": "Technology",
        "jobType": "Full-time",
        "experienceLevel": "Mid-level",
        "postedDate": "2025-07-25",
        "salaryRange": {"min": 500000, "max": 800000, "currency": "RWF"},
        "required_skills": ["python", "fastapi", "sql", "docker", "git"]
    },
    {
        "id": 4,
        "title": "Full-stack Developer",
        "company": "Go Kigali",
        "location": "Kigali, Rwanda",
        "industry": "Tourism",
        "jobType": "Full-time",
        "experienceLevel": "Senior",
        "postedDate": "2025-08-05",
        "salaryRange": {"min": 600000, "max": 1000000, "currency": "RWF"},
        "required_skills": ["html", "css", "javascript", "react", "python", "fastapi", "sql", "git"]
    },
    {
        "id": 5,
        "title": "Data Analyst",
        "company": "Bank of Kigali",
        "location": "Kigali, Rwanda",
        "industry": "Banking",
        "jobType": "Full-time",
        "experienceLevel": "Entry",
        "postedDate": "2025-08-02",
        "salaryRange": {"min": 400000, "max": 700000, "currency": "RWF"},
        "required_skills": ["python", "pandas", "numpy", "sql", "powerbi"]
    },
    {
        "id": 6,
        "title": "Digital Marketing Specialist",
        "company": "RwandaAir",
        "location": "Kigali, Rwanda",
        "industry": "Travel",
        "jobType": "Contract",
        "experienceLevel": "Mid-level",
        "postedDate": "2025-07-30",
        "salaryRange": {"min": 300000, "max": 500000, "currency": "RWF"},
        "required_skills": ["seo", "sem", "social media marketing", "google analytics"]
    },
    {
        "id": 7,
        "title": "Fintech Product Manager",
        "company": "MTN Rwanda",
        "location": "Kigali, Rwanda",
        "industry": "Fintech",
        "jobType": "Full-time",
        "experienceLevel": "Senior",
        "postedDate": "2025-08-04",
        "salaryRange": {"min": 800000, "max": 1500000, "currency": "RWF"},
        "required_skills": ["product management", "fintech", "agile", "data analysis"]
    },
    {
        "id": 8,
        "title": "IT Support Technician",
        "company": "University of Rwanda",
        "location": "Kigali, Rwanda",
        "industry": "Education",
        "jobType": "Full-time",
        "experienceLevel": "Entry",
        "postedDate": "2025-07-29",
        "salaryRange": {"min": 250000, "max": 400000, "currency": "RWF"},
        "required_skills": ["hardware", "troubleshooting", "networking basics"]
    },
    {
        "id": 9,
        "title": "Junior Data Analyst (Banking)",
        "company": "Equity Bank Rwanda",
        "location": "Kigali, Rwanda",
        "industry": "Banking",
        "jobType": "Full-time",
        "experienceLevel": "Entry",
        "postedDate": "2025-08-03",
        "salaryRange": {"min": 450000, "max": 650000, "currency": "RWF"},
        "required_skills": ["sql", "excel", "powerbi"]
    },
    {
        "id": 10,
        "title": "Content & SEO Specialist",
        "company": "Vuba Vuba",
        "location": "Remote",
        "industry": "E-commerce",
        "jobType": "Full-time",
        "experienceLevel": "Mid-level",
        "postedDate": "2025-07-27",
        "salaryRange": {"min": 300000, "max": 500000, "currency": "RWF"},
        "required_skills": ["seo", "content marketing", "google analytics"]
    },
    {
        "id": 11,
        "title": "Mobile Money Integration Dev",
        "company": "Airtel Rwanda",
        "location": "Kigali, Rwanda",
        "industry": "Fintech",
        "jobType": "Full-time",
        "experienceLevel": "Senior",
        "postedDate": "2025-08-01",
        "salaryRange": {"min": 700000, "max": 1200000, "currency": "RWF"},
        "required_skills": ["javascript", "node", "api integration", "fintech"]
    },
    {
        "id": 12,
        "title": "Frontend Developer (React)",
        "company": "Irembo",
        "location": "Kigali, Rwanda",
        "industry": "Government",
        "jobType": "Full-time",
        "experienceLevel": "Mid-level",
        "postedDate": "2025-07-26",
        "salaryRange": {"min": 500000, "max": 800000, "currency": "RWF"},
        "required_skills": ["html", "css", "javascript", "react", "git"]
    }
]

RESOURCES = {
    "html": "https://www.youtube.com/watch?v=kUMe1FH4paE",
    "css": "https://www.youtube.com/watch?v=OEV8gHs_a38",
    "javascript": "https://www.youtube.com/watch?v=PkZNo7MFNFg",
    "react": "https://www.youtube.com/watch?v=bMknfKXIFA8",
    "python": "https://www.youtube.com/watch?v=rfscVS0vtbw",
    "fastapi": "https://www.youtube.com/watch?v=7t2alSnE2-I",
    "sql": "https://www.youtube.com/watch?v=HXV3zeQKqGY",
    "git": "https://www.youtube.com/watch?v=RGOj5yH7evk",
    "docker": "https://www.youtube.com/watch?v=3c-iBn73dDE",
    "pandas": "https://www.youtube.com/watch?v=vmEHCJofslg",
    "numpy": "https://www.youtube.com/watch?v=QUT1VHiLmmI",
    "powerbi": "https://www.youtube.com/watch?v=3u7MQz1EyPY",
    "seo": "https://www.youtube.com/watch?v=sSW_93qPApA",
    "sem": "https://www.youtube.com/watch?v=Pj2s1_yOotY",
    "social media marketing": "https://www.youtube.com/watch?v=s_t4-a_a7A8",
    "google analytics": "https://www.youtube.com/watch?v=uG9y_m6_3w0",
    "product management": "https://www.youtube.com/watch?v=T2-A3d3-2_s",
    "fintech": "https://www.youtube.com/watch?v=T2-A3d3-2_s",
    "agile": "https://www.youtube.com/watch?v=T2-A3d3-2_s",
    "data analysis": "https://www.youtube.com/watch?v=T2-A3d3-2_s"
}
